import type { Metadata } from "next";
import { Geist, Geist_Mono, Instrument_Sans } from "next/font/google";
import "./globals.css";
import ReduxProvider from "./components/ReduxProvider";
import GradientBackground from "./components/GradientBackground";

const instrumentSans = Instrument_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${instrumentSans}} antialiased relative min-h-screen bg-[hsla(224,25%,60%,1)] flex py-10 items-center`}
            >
                <GradientBackground />
                <ReduxProvider>{children}</ReduxProvider>
            </body>
        </html>
    );
}
